### ISSUE TITLE
How to calculate total score？

### ISSUE THREAD

**Issue by jiaxiangc** [Ji4chenLi/t2v-turbo#10]
Hi, we see you get SoTA result. I want to know how to calculate the total score？We donot know the weight per dimension.

**Comment by Ji4chenLi** [comment]
Hi,

You should find the answer by checking VBench's documentation. The `app.py` below should give you the answer.

https://huggingface.co/spaces/Vchitect/VBench_Leaderboard/blob/main/app.py

**Comment by jiaxiangc** [comment]
> Hi,
> 
> You should find the answer by checking VBench's documentation. The `app.py` below should give you the answer.
> 
> https://huggingface.co/spaces/Vchitect/VBench_Leaderboard/blob/main/app.py

Thanks for your reply.
