### ISSUE TITLE
Different generation outputs even though fixing the random seed 

### ISSUE THREAD

**Issue by daeunni** [Ji4chenLi/t2v-turbo#14]
Hi @Ji4chenLi , I am using the T2V-Turbo (VC2) model and fixing the random seed like below. 
```python
def generate(
    prompt: str,
    seed: int = 123,                            # Seed fix (123)
    guidance_scale: float = 7.5,
    num_inference_steps: int = 4,
    num_frames: int = 16,
    fps: int = 16,
    randomize_seed: bool = False,  # Set False 
    ... 
``` 
However, even though I fixed random seed =123, the generation results from the prompt "A family of three take their dog and cat for a walk in the park, enjoying the fresh air and exercise" are not the same. (Please refer to the below figure)
<img width="592" alt="image" src="https://github.com/user-attachments/assets/c4d80e7d-e4ff-441f-939b-2d2f0fdf2230">

Why is it happening? How can I fix the generation results? Thanks!

**Comment by DancinBit** [comment]
try 
```
from lightning_fabric import seed_everything
...
seed_everything(seed)
```

**Comment by daeunni** [comment]
I found it still isn't working. Is there any methodological cause for this? I would appreciate you share any idea. Thanks!

**Comment by DancinBit** [comment]
use seed_everything before initializing noise latents🤪

**Comment by Ji4chenLi** [comment]
I'll fix this issue in our next update very soon (within 2 days)! Stay tuned!

**Comment by Ji4chenLi** [comment]
The new version is up.

**Comment by danielajisafe** [comment]
This problem is not fixed yet - @Ji4chenLi please can you share thoughts on any part of the pipeline/method that could be a suspect?

**Comment by daeunni** [comment]
yes still not fixed. I observed different outputs per different gpus even though I fixed every random seeds.
