### ISSUE TITLE
question about inference and data

### ISSUE THREAD

**Issue by dreamyou070** [Ji4chenLi/t2v-turbo#16]
1) I tried to inference of video crafter2. But the videos that i get like the videos below ....
    I used VideoCrafter2 pretrained weight as a base and Unet Lora.
    Can you recommend any other way?

https://github.com/user-attachments/assets/400fb9a0-456e-4daa-ad1c-11c20cb1d173

2) Second question is,
     I want to train model with  Webvid dataset, 
     However the dataset is no longer available,
     Can you recommend another way?

**Comment by t2v-turbo-v2** [comment]
Thanks for the question.

> I tried to inference of video crafter2

Are you trying to do inference with VideoCrafter2 or our T2V-Turbo (VC2)?

> Can you recommend any other way?

We uploaded merged weights at https://huggingface.co/jiachenli-ucsb/T2V-Turbo-VC2-Merged. You can try directly loading it.

> I want to train model with Webvid dataset. However the dataset is no longer available. Can you recommend another way?

We cannot help you with this issue. However, you can try to find advice on WebVid's official repo.

**Comment by Ji4chenLi** [comment]
Thanks for the question.

> I tried to inference of video crafter2

Are you trying to do inference with VideoCrafter2 or our T2V-Turbo (VC2)?

> Can you recommend any other way?

We uploaded merged weights at https://huggingface.co/jiachenli-ucsb/T2V-Turbo-VC2-Merged. You can try directly loading it.

> I want to train model with Webvid dataset. However the dataset is no longer available. Can you recommend another way?

We cannot help you with this issue. However, you can try to find advice on WebVid's official repo.
