### ISSUE TITLE
licensing of this repository?

### ISSUE THREAD

**Issue by githubloader** [Ji4chenLi/t2v-turbo#21]
Could you please provide information about the licensing of this repository? thx!

**Comment by Ji4chenLi** [comment]
Our model is distilled from VideoCrafter2. So, our license should follow VideoCrafter2's lessons. Other than that, we don't restrict the model. Moroever, our model is meant for research purposes.

It is prohibited to generate content that is demeaning or harmful to people or their environment, culture, religion, etc.
Prohibited for pornographic, violent, and bloody content generation.
Prohibited for error and false information generation.
