### ISSUE TITLE
Could you share your VBench Videos?

### ISSUE THREAD

**Issue by Syzygianinfern0** [Ji4chenLi/t2v-turbo#23]
Is it possible for you to upload the videos that were used for VBench evaluation?

**Comment by Syzygianinfern0** [comment]
@Ji4chenLi @lalalune @chenxwh do you think it would be possible to share these videos? We are working on a new metric for Text-to-Video models and would like to use the videos you use for VBench evaluation.

**Comment by Ji4chenLi** [comment]
Hi,

Sorry for the late reply. Here is the link to the VBench videos. https://drive.google.com/file/d/1LhomqUq7RONcYgUolPdCRqm2jJeCXWv0/view?usp=drive_link

**Comment by Syzygianinfern0** [comment]
Thank you so much!
