### ISSUE TITLE
flash-attn error in InternVideo2

### ISSUE THREAD

**Issue by huangjch526** [Ji4chenLi/t2v-turbo#26]
Can you help me? I installed flash-attn 2.6.3 and cd csrc/layer_norm && pip install . in order to use InternVideo2, but when I in:
from flash_attn.ops.rms_norm import DropoutAddRMSNorm
I meet
import dropout_layer_norm
it reports a segment error and I've spent a day trying to find out what the cause.

**Comment by danielajisafe** [comment]
@huangjch526 please how did you fix the layer_norm installation issue?
