### ISSUE TITLE
The Training Scripts

### ISSUE THREAD

**Issue by haohang96** [Ji4chenLi/t2v-turbo#3]
Thanks for the open source of your excellent work

The README gives command lines for training. But I can not find the corresponding script "train_t2v_turbo_vc2.sh".

Could you help check this issue?

Thanks

**Comment by Ji4chenLi** [comment]
Hi Hao,

Thanks for your interest in our work. We are working on the training code release. Please stay tuned!

Best,
Jiachen

**Comment by xiao2mo** [comment]
the training code?

**Comment by xiao2mo** [comment]
> Hi Hao,
> 
> Thanks for your interest in our work. We are working on the training code release. Please stay tuned!
> 
> Best, Jiachen

Hi，any time plan for training release

**Comment by Ji4chenLi** [comment]
The training codes are now released!
