### ISSUE TITLE
Automatic Killing of Process while inferencing: 

### ISSUE THREAD

**Issue by GARV-k** [Ji4chenLi/t2v-turbo#7]
My command :  python app.py --unet_dir unet_lora.pt --base_model_dir
 model.ckpt
  Output : 
/home/garv/garv/lib/python3.10/site-packages/diffusers/models/transformers/transformer_2d.py:34: FutureWarning: `Transformer2DModelOutput` is deprecated and will be removed in version 1.0.0. Importing `Transformer2DModelOutput` from `diffusers.models.transformer_2d` is deprecated and this will be removed in a future version. Please use `from diffusers.models.modeling_outputs import Transformer2DModelOutput`, instead.
  deprecate("Transformer2DModelOutput", "1.0.0", deprecation_message)
AE working on z of shape (1, 4, 64, 64) = 16384 dimensions.
Killed

P.S : I have tried on google Colab. I have tried it on WSL 22.04. the process automatically kills itself. 
Repo maintainers please help with a solution to this.

**Comment by Ji4chenLi** [comment]
Could you provide more context about "the process automatically kills itself"? For example, is there any error msg?
