### ISSUE TITLE
Looks like all generated images are in "water painting" style

### ISSUE THREAD

**Issue by Tonniia** [Ji4chenLi/t2v-turbo#9]
Hi. It seems that the generated images are in water painting style?

**Comment by Ji4chenLi** [comment]
It depends on your prompts. The general style should be inherited from the HPSv2.1 text-image reward model. Feel free to train your own t2v-turbo with different reward models.

**Comment by Youne-Yu** [comment]
> Hi. It seems that the generated images are in water painting style?
This problem also occurs when I use prompt words outside of the project's home page
